# SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: compute.gcp-beta.m.upbound.io/v1beta1
kind: RegionBackendService
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/regionbackendservice
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    connectionDrainingTimeoutSec: 10
    healthChecksRefs:
    - name: default
    region: us-central1
    sessionAffinity: CLIENT_IP
---
apiVersion: compute.gcp-beta.m.upbound.io/v1beta1
kind: HealthCheck
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/regionbackendservice
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    checkIntervalSec: 1
    tcpHealthCheck:
      port: 80
    timeoutSec: 1
