# SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
#
# SPDX-License-Identifier: Apache-2.0

version: "2"

run:
  timeout: 60m

output:
  formats:
    colored-line-number: {}

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/upbound/provider-gcp-beta

linters:
  default: none
  enable:
    - govet
    - gocyclo
    - gocritic
    - goconst
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - misspell
    - nakedret

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-files:
        - fmt:.*,io/ioutil:^Read.*

    govet:
      check-shadowing: false

    revive:
      confidence: 0.8

    gocyclo:
      min-complexity: 10

    dupl:
      threshold: 100

    goconst:
      min-len: 3
      min-occurrences: 5

    lll:
      tab-width: 1

    unused:
      check-exported: false

    unparam:
      check-exported: false

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    gocritic:
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test(ing)?\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - unparam

      - path: _test\.go
        text: "(unnamedResult|exitAfterDefer)"
        linters:
          - gocritic

      - text: "(hugeParam|rangeValCopy):"
        linters:
          - gocritic

      - text: "SA3000:"
        linters:
          - staticcheck

      - text: "G101:"
        linters:
          - gosec

      - text: "G104:"
        linters:
          - gosec

issues:
  exclude-files:
    - "zz_\\..+\\.go$"
  new: false
  max-per-linter: 0
  max-same-issues: 0
