# SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: networksecurity.gcp-beta.m.upbound.io/v1beta1
kind: ServerTLSPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: networksecurity/v1beta1/servertlspolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    location: global
    allowOpen: false
    description: my description
    labels:
      foo: bar
    mtlsPolicy:
      clientValidationCa:
      - grpcEndpoint:
          targetUri: unix:mypath
    serverCertificate:
      certificateProviderInstance:
        pluginInstance: google_cloud_private_spiffe
