//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeCompilationConfigInitParameters) DeepCopyInto(out *CodeCompilationConfigInitParameters) {
	*out = *in
	if in.AssertionSchema != nil {
		in, out := &in.AssertionSchema, &out.AssertionSchema
		*out = new(string)
		**out = **in
	}
	if in.DatabaseSuffix != nil {
		in, out := &in.DatabaseSuffix, &out.DatabaseSuffix
		*out = new(string)
		**out = **in
	}
	if in.DefaultDatabase != nil {
		in, out := &in.DefaultDatabase, &out.DefaultDatabase
		*out = new(string)
		**out = **in
	}
	if in.DefaultLocation != nil {
		in, out := &in.DefaultLocation, &out.DefaultLocation
		*out = new(string)
		**out = **in
	}
	if in.DefaultSchema != nil {
		in, out := &in.DefaultSchema, &out.DefaultSchema
		*out = new(string)
		**out = **in
	}
	if in.SchemaSuffix != nil {
		in, out := &in.SchemaSuffix, &out.SchemaSuffix
		*out = new(string)
		**out = **in
	}
	if in.TablePrefix != nil {
		in, out := &in.TablePrefix, &out.TablePrefix
		*out = new(string)
		**out = **in
	}
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeCompilationConfigInitParameters.
func (in *CodeCompilationConfigInitParameters) DeepCopy() *CodeCompilationConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(CodeCompilationConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeCompilationConfigObservation) DeepCopyInto(out *CodeCompilationConfigObservation) {
	*out = *in
	if in.AssertionSchema != nil {
		in, out := &in.AssertionSchema, &out.AssertionSchema
		*out = new(string)
		**out = **in
	}
	if in.DatabaseSuffix != nil {
		in, out := &in.DatabaseSuffix, &out.DatabaseSuffix
		*out = new(string)
		**out = **in
	}
	if in.DefaultDatabase != nil {
		in, out := &in.DefaultDatabase, &out.DefaultDatabase
		*out = new(string)
		**out = **in
	}
	if in.DefaultLocation != nil {
		in, out := &in.DefaultLocation, &out.DefaultLocation
		*out = new(string)
		**out = **in
	}
	if in.DefaultSchema != nil {
		in, out := &in.DefaultSchema, &out.DefaultSchema
		*out = new(string)
		**out = **in
	}
	if in.SchemaSuffix != nil {
		in, out := &in.SchemaSuffix, &out.SchemaSuffix
		*out = new(string)
		**out = **in
	}
	if in.TablePrefix != nil {
		in, out := &in.TablePrefix, &out.TablePrefix
		*out = new(string)
		**out = **in
	}
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeCompilationConfigObservation.
func (in *CodeCompilationConfigObservation) DeepCopy() *CodeCompilationConfigObservation {
	if in == nil {
		return nil
	}
	out := new(CodeCompilationConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeCompilationConfigParameters) DeepCopyInto(out *CodeCompilationConfigParameters) {
	*out = *in
	if in.AssertionSchema != nil {
		in, out := &in.AssertionSchema, &out.AssertionSchema
		*out = new(string)
		**out = **in
	}
	if in.DatabaseSuffix != nil {
		in, out := &in.DatabaseSuffix, &out.DatabaseSuffix
		*out = new(string)
		**out = **in
	}
	if in.DefaultDatabase != nil {
		in, out := &in.DefaultDatabase, &out.DefaultDatabase
		*out = new(string)
		**out = **in
	}
	if in.DefaultLocation != nil {
		in, out := &in.DefaultLocation, &out.DefaultLocation
		*out = new(string)
		**out = **in
	}
	if in.DefaultSchema != nil {
		in, out := &in.DefaultSchema, &out.DefaultSchema
		*out = new(string)
		**out = **in
	}
	if in.SchemaSuffix != nil {
		in, out := &in.SchemaSuffix, &out.SchemaSuffix
		*out = new(string)
		**out = **in
	}
	if in.TablePrefix != nil {
		in, out := &in.TablePrefix, &out.TablePrefix
		*out = new(string)
		**out = **in
	}
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeCompilationConfigParameters.
func (in *CodeCompilationConfigParameters) DeepCopy() *CodeCompilationConfigParameters {
	if in == nil {
		return nil
	}
	out := new(CodeCompilationConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionInitParameters) DeepCopyInto(out *ConditionInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionInitParameters.
func (in *ConditionInitParameters) DeepCopy() *ConditionInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionObservation) DeepCopyInto(out *ConditionObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionObservation.
func (in *ConditionObservation) DeepCopy() *ConditionObservation {
	if in == nil {
		return nil
	}
	out := new(ConditionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionParameters) DeepCopyInto(out *ConditionParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionParameters.
func (in *ConditionParameters) DeepCopy() *ConditionParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorStatusInitParameters) DeepCopyInto(out *ErrorStatusInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorStatusInitParameters.
func (in *ErrorStatusInitParameters) DeepCopy() *ErrorStatusInitParameters {
	if in == nil {
		return nil
	}
	out := new(ErrorStatusInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorStatusObservation) DeepCopyInto(out *ErrorStatusObservation) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(float64)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorStatusObservation.
func (in *ErrorStatusObservation) DeepCopy() *ErrorStatusObservation {
	if in == nil {
		return nil
	}
	out := new(ErrorStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorStatusParameters) DeepCopyInto(out *ErrorStatusParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorStatusParameters.
func (in *ErrorStatusParameters) DeepCopy() *ErrorStatusParameters {
	if in == nil {
		return nil
	}
	out := new(ErrorStatusParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRemoteSettingsInitParameters) DeepCopyInto(out *GitRemoteSettingsInitParameters) {
	*out = *in
	if in.AuthenticationTokenSecretVersion != nil {
		in, out := &in.AuthenticationTokenSecretVersion, &out.AuthenticationTokenSecretVersion
		*out = new(string)
		**out = **in
	}
	if in.DefaultBranch != nil {
		in, out := &in.DefaultBranch, &out.DefaultBranch
		*out = new(string)
		**out = **in
	}
	if in.SSHAuthenticationConfig != nil {
		in, out := &in.SSHAuthenticationConfig, &out.SSHAuthenticationConfig
		*out = new(SSHAuthenticationConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRemoteSettingsInitParameters.
func (in *GitRemoteSettingsInitParameters) DeepCopy() *GitRemoteSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(GitRemoteSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRemoteSettingsObservation) DeepCopyInto(out *GitRemoteSettingsObservation) {
	*out = *in
	if in.AuthenticationTokenSecretVersion != nil {
		in, out := &in.AuthenticationTokenSecretVersion, &out.AuthenticationTokenSecretVersion
		*out = new(string)
		**out = **in
	}
	if in.DefaultBranch != nil {
		in, out := &in.DefaultBranch, &out.DefaultBranch
		*out = new(string)
		**out = **in
	}
	if in.SSHAuthenticationConfig != nil {
		in, out := &in.SSHAuthenticationConfig, &out.SSHAuthenticationConfig
		*out = new(SSHAuthenticationConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.TokenStatus != nil {
		in, out := &in.TokenStatus, &out.TokenStatus
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRemoteSettingsObservation.
func (in *GitRemoteSettingsObservation) DeepCopy() *GitRemoteSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(GitRemoteSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRemoteSettingsParameters) DeepCopyInto(out *GitRemoteSettingsParameters) {
	*out = *in
	if in.AuthenticationTokenSecretVersion != nil {
		in, out := &in.AuthenticationTokenSecretVersion, &out.AuthenticationTokenSecretVersion
		*out = new(string)
		**out = **in
	}
	if in.DefaultBranch != nil {
		in, out := &in.DefaultBranch, &out.DefaultBranch
		*out = new(string)
		**out = **in
	}
	if in.SSHAuthenticationConfig != nil {
		in, out := &in.SSHAuthenticationConfig, &out.SSHAuthenticationConfig
		*out = new(SSHAuthenticationConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRemoteSettingsParameters.
func (in *GitRemoteSettingsParameters) DeepCopy() *GitRemoteSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(GitRemoteSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludedTargetsInitParameters) DeepCopyInto(out *IncludedTargetsInitParameters) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludedTargetsInitParameters.
func (in *IncludedTargetsInitParameters) DeepCopy() *IncludedTargetsInitParameters {
	if in == nil {
		return nil
	}
	out := new(IncludedTargetsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludedTargetsObservation) DeepCopyInto(out *IncludedTargetsObservation) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludedTargetsObservation.
func (in *IncludedTargetsObservation) DeepCopy() *IncludedTargetsObservation {
	if in == nil {
		return nil
	}
	out := new(IncludedTargetsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludedTargetsParameters) DeepCopyInto(out *IncludedTargetsParameters) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludedTargetsParameters.
func (in *IncludedTargetsParameters) DeepCopy() *IncludedTargetsParameters {
	if in == nil {
		return nil
	}
	out := new(IncludedTargetsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvocationConfigInitParameters) DeepCopyInto(out *InvocationConfigInitParameters) {
	*out = *in
	if in.FullyRefreshIncrementalTablesEnabled != nil {
		in, out := &in.FullyRefreshIncrementalTablesEnabled, &out.FullyRefreshIncrementalTablesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IncludedTags != nil {
		in, out := &in.IncludedTags, &out.IncludedTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IncludedTargets != nil {
		in, out := &in.IncludedTargets, &out.IncludedTargets
		*out = make([]IncludedTargetsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccountRef != nil {
		in, out := &in.ServiceAccountRef, &out.ServiceAccountRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccountSelector != nil {
		in, out := &in.ServiceAccountSelector, &out.ServiceAccountSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.TransitiveDependenciesIncluded != nil {
		in, out := &in.TransitiveDependenciesIncluded, &out.TransitiveDependenciesIncluded
		*out = new(bool)
		**out = **in
	}
	if in.TransitiveDependentsIncluded != nil {
		in, out := &in.TransitiveDependentsIncluded, &out.TransitiveDependentsIncluded
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvocationConfigInitParameters.
func (in *InvocationConfigInitParameters) DeepCopy() *InvocationConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(InvocationConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvocationConfigObservation) DeepCopyInto(out *InvocationConfigObservation) {
	*out = *in
	if in.FullyRefreshIncrementalTablesEnabled != nil {
		in, out := &in.FullyRefreshIncrementalTablesEnabled, &out.FullyRefreshIncrementalTablesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IncludedTags != nil {
		in, out := &in.IncludedTags, &out.IncludedTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IncludedTargets != nil {
		in, out := &in.IncludedTargets, &out.IncludedTargets
		*out = make([]IncludedTargetsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.TransitiveDependenciesIncluded != nil {
		in, out := &in.TransitiveDependenciesIncluded, &out.TransitiveDependenciesIncluded
		*out = new(bool)
		**out = **in
	}
	if in.TransitiveDependentsIncluded != nil {
		in, out := &in.TransitiveDependentsIncluded, &out.TransitiveDependentsIncluded
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvocationConfigObservation.
func (in *InvocationConfigObservation) DeepCopy() *InvocationConfigObservation {
	if in == nil {
		return nil
	}
	out := new(InvocationConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvocationConfigParameters) DeepCopyInto(out *InvocationConfigParameters) {
	*out = *in
	if in.FullyRefreshIncrementalTablesEnabled != nil {
		in, out := &in.FullyRefreshIncrementalTablesEnabled, &out.FullyRefreshIncrementalTablesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IncludedTags != nil {
		in, out := &in.IncludedTags, &out.IncludedTags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IncludedTargets != nil {
		in, out := &in.IncludedTargets, &out.IncludedTargets
		*out = make([]IncludedTargetsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccountRef != nil {
		in, out := &in.ServiceAccountRef, &out.ServiceAccountRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccountSelector != nil {
		in, out := &in.ServiceAccountSelector, &out.ServiceAccountSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.TransitiveDependenciesIncluded != nil {
		in, out := &in.TransitiveDependenciesIncluded, &out.TransitiveDependenciesIncluded
		*out = new(bool)
		**out = **in
	}
	if in.TransitiveDependentsIncluded != nil {
		in, out := &in.TransitiveDependentsIncluded, &out.TransitiveDependentsIncluded
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvocationConfigParameters.
func (in *InvocationConfigParameters) DeepCopy() *InvocationConfigParameters {
	if in == nil {
		return nil
	}
	out := new(InvocationConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentScheduledExecutionRecordsErrorStatusInitParameters) DeepCopyInto(out *RecentScheduledExecutionRecordsErrorStatusInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentScheduledExecutionRecordsErrorStatusInitParameters.
func (in *RecentScheduledExecutionRecordsErrorStatusInitParameters) DeepCopy() *RecentScheduledExecutionRecordsErrorStatusInitParameters {
	if in == nil {
		return nil
	}
	out := new(RecentScheduledExecutionRecordsErrorStatusInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentScheduledExecutionRecordsErrorStatusObservation) DeepCopyInto(out *RecentScheduledExecutionRecordsErrorStatusObservation) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(float64)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentScheduledExecutionRecordsErrorStatusObservation.
func (in *RecentScheduledExecutionRecordsErrorStatusObservation) DeepCopy() *RecentScheduledExecutionRecordsErrorStatusObservation {
	if in == nil {
		return nil
	}
	out := new(RecentScheduledExecutionRecordsErrorStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentScheduledExecutionRecordsErrorStatusParameters) DeepCopyInto(out *RecentScheduledExecutionRecordsErrorStatusParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentScheduledExecutionRecordsErrorStatusParameters.
func (in *RecentScheduledExecutionRecordsErrorStatusParameters) DeepCopy() *RecentScheduledExecutionRecordsErrorStatusParameters {
	if in == nil {
		return nil
	}
	out := new(RecentScheduledExecutionRecordsErrorStatusParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentScheduledExecutionRecordsInitParameters) DeepCopyInto(out *RecentScheduledExecutionRecordsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentScheduledExecutionRecordsInitParameters.
func (in *RecentScheduledExecutionRecordsInitParameters) DeepCopy() *RecentScheduledExecutionRecordsInitParameters {
	if in == nil {
		return nil
	}
	out := new(RecentScheduledExecutionRecordsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentScheduledExecutionRecordsObservation) DeepCopyInto(out *RecentScheduledExecutionRecordsObservation) {
	*out = *in
	if in.ErrorStatus != nil {
		in, out := &in.ErrorStatus, &out.ErrorStatus
		*out = make([]RecentScheduledExecutionRecordsErrorStatusObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExecutionTime != nil {
		in, out := &in.ExecutionTime, &out.ExecutionTime
		*out = new(string)
		**out = **in
	}
	if in.WorkflowInvocation != nil {
		in, out := &in.WorkflowInvocation, &out.WorkflowInvocation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentScheduledExecutionRecordsObservation.
func (in *RecentScheduledExecutionRecordsObservation) DeepCopy() *RecentScheduledExecutionRecordsObservation {
	if in == nil {
		return nil
	}
	out := new(RecentScheduledExecutionRecordsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentScheduledExecutionRecordsParameters) DeepCopyInto(out *RecentScheduledExecutionRecordsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentScheduledExecutionRecordsParameters.
func (in *RecentScheduledExecutionRecordsParameters) DeepCopy() *RecentScheduledExecutionRecordsParameters {
	if in == nil {
		return nil
	}
	out := new(RecentScheduledExecutionRecordsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentScheduledReleaseRecordsInitParameters) DeepCopyInto(out *RecentScheduledReleaseRecordsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentScheduledReleaseRecordsInitParameters.
func (in *RecentScheduledReleaseRecordsInitParameters) DeepCopy() *RecentScheduledReleaseRecordsInitParameters {
	if in == nil {
		return nil
	}
	out := new(RecentScheduledReleaseRecordsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentScheduledReleaseRecordsObservation) DeepCopyInto(out *RecentScheduledReleaseRecordsObservation) {
	*out = *in
	if in.CompilationResult != nil {
		in, out := &in.CompilationResult, &out.CompilationResult
		*out = new(string)
		**out = **in
	}
	if in.ErrorStatus != nil {
		in, out := &in.ErrorStatus, &out.ErrorStatus
		*out = make([]ErrorStatusObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReleaseTime != nil {
		in, out := &in.ReleaseTime, &out.ReleaseTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentScheduledReleaseRecordsObservation.
func (in *RecentScheduledReleaseRecordsObservation) DeepCopy() *RecentScheduledReleaseRecordsObservation {
	if in == nil {
		return nil
	}
	out := new(RecentScheduledReleaseRecordsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentScheduledReleaseRecordsParameters) DeepCopyInto(out *RecentScheduledReleaseRecordsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentScheduledReleaseRecordsParameters.
func (in *RecentScheduledReleaseRecordsParameters) DeepCopy() *RecentScheduledReleaseRecordsParameters {
	if in == nil {
		return nil
	}
	out := new(RecentScheduledReleaseRecordsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Repository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryIAMMember) DeepCopyInto(out *RepositoryIAMMember) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryIAMMember.
func (in *RepositoryIAMMember) DeepCopy() *RepositoryIAMMember {
	if in == nil {
		return nil
	}
	out := new(RepositoryIAMMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryIAMMember) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryIAMMemberInitParameters) DeepCopyInto(out *RepositoryIAMMemberInitParameters) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(ConditionInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Member != nil {
		in, out := &in.Member, &out.Member
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositorySelector != nil {
		in, out := &in.RepositorySelector, &out.RepositorySelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryIAMMemberInitParameters.
func (in *RepositoryIAMMemberInitParameters) DeepCopy() *RepositoryIAMMemberInitParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryIAMMemberInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryIAMMemberList) DeepCopyInto(out *RepositoryIAMMemberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepositoryIAMMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryIAMMemberList.
func (in *RepositoryIAMMemberList) DeepCopy() *RepositoryIAMMemberList {
	if in == nil {
		return nil
	}
	out := new(RepositoryIAMMemberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryIAMMemberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryIAMMemberObservation) DeepCopyInto(out *RepositoryIAMMemberObservation) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(ConditionObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Etag != nil {
		in, out := &in.Etag, &out.Etag
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Member != nil {
		in, out := &in.Member, &out.Member
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryIAMMemberObservation.
func (in *RepositoryIAMMemberObservation) DeepCopy() *RepositoryIAMMemberObservation {
	if in == nil {
		return nil
	}
	out := new(RepositoryIAMMemberObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryIAMMemberParameters) DeepCopyInto(out *RepositoryIAMMemberParameters) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(ConditionParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Member != nil {
		in, out := &in.Member, &out.Member
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositorySelector != nil {
		in, out := &in.RepositorySelector, &out.RepositorySelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryIAMMemberParameters.
func (in *RepositoryIAMMemberParameters) DeepCopy() *RepositoryIAMMemberParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryIAMMemberParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryIAMMemberSpec) DeepCopyInto(out *RepositoryIAMMemberSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryIAMMemberSpec.
func (in *RepositoryIAMMemberSpec) DeepCopy() *RepositoryIAMMemberSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryIAMMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryIAMMemberStatus) DeepCopyInto(out *RepositoryIAMMemberStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryIAMMemberStatus.
func (in *RepositoryIAMMemberStatus) DeepCopy() *RepositoryIAMMemberStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryIAMMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryInitParameters) DeepCopyInto(out *RepositoryInitParameters) {
	*out = *in
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.GitRemoteSettings != nil {
		in, out := &in.GitRemoteSettings, &out.GitRemoteSettings
		*out = new(GitRemoteSettingsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.KMSKeyName != nil {
		in, out := &in.KMSKeyName, &out.KMSKeyName
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.NpmrcEnvironmentVariablesSecretVersion != nil {
		in, out := &in.NpmrcEnvironmentVariablesSecretVersion, &out.NpmrcEnvironmentVariablesSecretVersion
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.WorkspaceCompilationOverrides != nil {
		in, out := &in.WorkspaceCompilationOverrides, &out.WorkspaceCompilationOverrides
		*out = new(WorkspaceCompilationOverridesInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryInitParameters.
func (in *RepositoryInitParameters) DeepCopy() *RepositoryInitParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryList) DeepCopyInto(out *RepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryList.
func (in *RepositoryList) DeepCopy() *RepositoryList {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryObservation) DeepCopyInto(out *RepositoryObservation) {
	*out = *in
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EffectiveLabels != nil {
		in, out := &in.EffectiveLabels, &out.EffectiveLabels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.GitRemoteSettings != nil {
		in, out := &in.GitRemoteSettings, &out.GitRemoteSettings
		*out = new(GitRemoteSettingsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyName != nil {
		in, out := &in.KMSKeyName, &out.KMSKeyName
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.NpmrcEnvironmentVariablesSecretVersion != nil {
		in, out := &in.NpmrcEnvironmentVariablesSecretVersion, &out.NpmrcEnvironmentVariablesSecretVersion
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.TerraformLabels != nil {
		in, out := &in.TerraformLabels, &out.TerraformLabels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.WorkspaceCompilationOverrides != nil {
		in, out := &in.WorkspaceCompilationOverrides, &out.WorkspaceCompilationOverrides
		*out = new(WorkspaceCompilationOverridesObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryObservation.
func (in *RepositoryObservation) DeepCopy() *RepositoryObservation {
	if in == nil {
		return nil
	}
	out := new(RepositoryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryParameters) DeepCopyInto(out *RepositoryParameters) {
	*out = *in
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.GitRemoteSettings != nil {
		in, out := &in.GitRemoteSettings, &out.GitRemoteSettings
		*out = new(GitRemoteSettingsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.KMSKeyName != nil {
		in, out := &in.KMSKeyName, &out.KMSKeyName
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.NpmrcEnvironmentVariablesSecretVersion != nil {
		in, out := &in.NpmrcEnvironmentVariablesSecretVersion, &out.NpmrcEnvironmentVariablesSecretVersion
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.WorkspaceCompilationOverrides != nil {
		in, out := &in.WorkspaceCompilationOverrides, &out.WorkspaceCompilationOverrides
		*out = new(WorkspaceCompilationOverridesParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryParameters.
func (in *RepositoryParameters) DeepCopy() *RepositoryParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryReleaseConfig) DeepCopyInto(out *RepositoryReleaseConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryReleaseConfig.
func (in *RepositoryReleaseConfig) DeepCopy() *RepositoryReleaseConfig {
	if in == nil {
		return nil
	}
	out := new(RepositoryReleaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryReleaseConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryReleaseConfigInitParameters) DeepCopyInto(out *RepositoryReleaseConfigInitParameters) {
	*out = *in
	if in.CodeCompilationConfig != nil {
		in, out := &in.CodeCompilationConfig, &out.CodeCompilationConfig
		*out = new(CodeCompilationConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.CronSchedule != nil {
		in, out := &in.CronSchedule, &out.CronSchedule
		*out = new(string)
		**out = **in
	}
	if in.GitCommitish != nil {
		in, out := &in.GitCommitish, &out.GitCommitish
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryReleaseConfigInitParameters.
func (in *RepositoryReleaseConfigInitParameters) DeepCopy() *RepositoryReleaseConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryReleaseConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryReleaseConfigList) DeepCopyInto(out *RepositoryReleaseConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepositoryReleaseConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryReleaseConfigList.
func (in *RepositoryReleaseConfigList) DeepCopy() *RepositoryReleaseConfigList {
	if in == nil {
		return nil
	}
	out := new(RepositoryReleaseConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryReleaseConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryReleaseConfigObservation) DeepCopyInto(out *RepositoryReleaseConfigObservation) {
	*out = *in
	if in.CodeCompilationConfig != nil {
		in, out := &in.CodeCompilationConfig, &out.CodeCompilationConfig
		*out = new(CodeCompilationConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.CronSchedule != nil {
		in, out := &in.CronSchedule, &out.CronSchedule
		*out = new(string)
		**out = **in
	}
	if in.GitCommitish != nil {
		in, out := &in.GitCommitish, &out.GitCommitish
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.RecentScheduledReleaseRecords != nil {
		in, out := &in.RecentScheduledReleaseRecords, &out.RecentScheduledReleaseRecords
		*out = make([]RecentScheduledReleaseRecordsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryReleaseConfigObservation.
func (in *RepositoryReleaseConfigObservation) DeepCopy() *RepositoryReleaseConfigObservation {
	if in == nil {
		return nil
	}
	out := new(RepositoryReleaseConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryReleaseConfigParameters) DeepCopyInto(out *RepositoryReleaseConfigParameters) {
	*out = *in
	if in.CodeCompilationConfig != nil {
		in, out := &in.CodeCompilationConfig, &out.CodeCompilationConfig
		*out = new(CodeCompilationConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.CronSchedule != nil {
		in, out := &in.CronSchedule, &out.CronSchedule
		*out = new(string)
		**out = **in
	}
	if in.GitCommitish != nil {
		in, out := &in.GitCommitish, &out.GitCommitish
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RegionRef != nil {
		in, out := &in.RegionRef, &out.RegionRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RegionSelector != nil {
		in, out := &in.RegionSelector, &out.RegionSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositorySelector != nil {
		in, out := &in.RepositorySelector, &out.RepositorySelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryReleaseConfigParameters.
func (in *RepositoryReleaseConfigParameters) DeepCopy() *RepositoryReleaseConfigParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryReleaseConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryReleaseConfigSpec) DeepCopyInto(out *RepositoryReleaseConfigSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryReleaseConfigSpec.
func (in *RepositoryReleaseConfigSpec) DeepCopy() *RepositoryReleaseConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryReleaseConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryReleaseConfigStatus) DeepCopyInto(out *RepositoryReleaseConfigStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryReleaseConfigStatus.
func (in *RepositoryReleaseConfigStatus) DeepCopy() *RepositoryReleaseConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryReleaseConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryStatus) DeepCopyInto(out *RepositoryStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryStatus.
func (in *RepositoryStatus) DeepCopy() *RepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWorkflowConfig) DeepCopyInto(out *RepositoryWorkflowConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWorkflowConfig.
func (in *RepositoryWorkflowConfig) DeepCopy() *RepositoryWorkflowConfig {
	if in == nil {
		return nil
	}
	out := new(RepositoryWorkflowConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryWorkflowConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWorkflowConfigInitParameters) DeepCopyInto(out *RepositoryWorkflowConfigInitParameters) {
	*out = *in
	if in.CronSchedule != nil {
		in, out := &in.CronSchedule, &out.CronSchedule
		*out = new(string)
		**out = **in
	}
	if in.InvocationConfig != nil {
		in, out := &in.InvocationConfig, &out.InvocationConfig
		*out = new(InvocationConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ReleaseConfig != nil {
		in, out := &in.ReleaseConfig, &out.ReleaseConfig
		*out = new(string)
		**out = **in
	}
	if in.ReleaseConfigRef != nil {
		in, out := &in.ReleaseConfigRef, &out.ReleaseConfigRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ReleaseConfigSelector != nil {
		in, out := &in.ReleaseConfigSelector, &out.ReleaseConfigSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWorkflowConfigInitParameters.
func (in *RepositoryWorkflowConfigInitParameters) DeepCopy() *RepositoryWorkflowConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryWorkflowConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWorkflowConfigList) DeepCopyInto(out *RepositoryWorkflowConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepositoryWorkflowConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWorkflowConfigList.
func (in *RepositoryWorkflowConfigList) DeepCopy() *RepositoryWorkflowConfigList {
	if in == nil {
		return nil
	}
	out := new(RepositoryWorkflowConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryWorkflowConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWorkflowConfigObservation) DeepCopyInto(out *RepositoryWorkflowConfigObservation) {
	*out = *in
	if in.CronSchedule != nil {
		in, out := &in.CronSchedule, &out.CronSchedule
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InvocationConfig != nil {
		in, out := &in.InvocationConfig, &out.InvocationConfig
		*out = new(InvocationConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.RecentScheduledExecutionRecords != nil {
		in, out := &in.RecentScheduledExecutionRecords, &out.RecentScheduledExecutionRecords
		*out = make([]RecentScheduledExecutionRecordsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReleaseConfig != nil {
		in, out := &in.ReleaseConfig, &out.ReleaseConfig
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWorkflowConfigObservation.
func (in *RepositoryWorkflowConfigObservation) DeepCopy() *RepositoryWorkflowConfigObservation {
	if in == nil {
		return nil
	}
	out := new(RepositoryWorkflowConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWorkflowConfigParameters) DeepCopyInto(out *RepositoryWorkflowConfigParameters) {
	*out = *in
	if in.CronSchedule != nil {
		in, out := &in.CronSchedule, &out.CronSchedule
		*out = new(string)
		**out = **in
	}
	if in.InvocationConfig != nil {
		in, out := &in.InvocationConfig, &out.InvocationConfig
		*out = new(InvocationConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.RegionRef != nil {
		in, out := &in.RegionRef, &out.RegionRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RegionSelector != nil {
		in, out := &in.RegionSelector, &out.RegionSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ReleaseConfig != nil {
		in, out := &in.ReleaseConfig, &out.ReleaseConfig
		*out = new(string)
		**out = **in
	}
	if in.ReleaseConfigRef != nil {
		in, out := &in.ReleaseConfigRef, &out.ReleaseConfigRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ReleaseConfigSelector != nil {
		in, out := &in.ReleaseConfigSelector, &out.ReleaseConfigSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositorySelector != nil {
		in, out := &in.RepositorySelector, &out.RepositorySelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWorkflowConfigParameters.
func (in *RepositoryWorkflowConfigParameters) DeepCopy() *RepositoryWorkflowConfigParameters {
	if in == nil {
		return nil
	}
	out := new(RepositoryWorkflowConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWorkflowConfigSpec) DeepCopyInto(out *RepositoryWorkflowConfigSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWorkflowConfigSpec.
func (in *RepositoryWorkflowConfigSpec) DeepCopy() *RepositoryWorkflowConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryWorkflowConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWorkflowConfigStatus) DeepCopyInto(out *RepositoryWorkflowConfigStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWorkflowConfigStatus.
func (in *RepositoryWorkflowConfigStatus) DeepCopy() *RepositoryWorkflowConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryWorkflowConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHAuthenticationConfigInitParameters) DeepCopyInto(out *SSHAuthenticationConfigInitParameters) {
	*out = *in
	if in.HostPublicKey != nil {
		in, out := &in.HostPublicKey, &out.HostPublicKey
		*out = new(string)
		**out = **in
	}
	if in.UserPrivateKeySecretVersion != nil {
		in, out := &in.UserPrivateKeySecretVersion, &out.UserPrivateKeySecretVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHAuthenticationConfigInitParameters.
func (in *SSHAuthenticationConfigInitParameters) DeepCopy() *SSHAuthenticationConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(SSHAuthenticationConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHAuthenticationConfigObservation) DeepCopyInto(out *SSHAuthenticationConfigObservation) {
	*out = *in
	if in.HostPublicKey != nil {
		in, out := &in.HostPublicKey, &out.HostPublicKey
		*out = new(string)
		**out = **in
	}
	if in.UserPrivateKeySecretVersion != nil {
		in, out := &in.UserPrivateKeySecretVersion, &out.UserPrivateKeySecretVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHAuthenticationConfigObservation.
func (in *SSHAuthenticationConfigObservation) DeepCopy() *SSHAuthenticationConfigObservation {
	if in == nil {
		return nil
	}
	out := new(SSHAuthenticationConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHAuthenticationConfigParameters) DeepCopyInto(out *SSHAuthenticationConfigParameters) {
	*out = *in
	if in.HostPublicKey != nil {
		in, out := &in.HostPublicKey, &out.HostPublicKey
		*out = new(string)
		**out = **in
	}
	if in.UserPrivateKeySecretVersion != nil {
		in, out := &in.UserPrivateKeySecretVersion, &out.UserPrivateKeySecretVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHAuthenticationConfigParameters.
func (in *SSHAuthenticationConfigParameters) DeepCopy() *SSHAuthenticationConfigParameters {
	if in == nil {
		return nil
	}
	out := new(SSHAuthenticationConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceCompilationOverridesInitParameters) DeepCopyInto(out *WorkspaceCompilationOverridesInitParameters) {
	*out = *in
	if in.DefaultDatabase != nil {
		in, out := &in.DefaultDatabase, &out.DefaultDatabase
		*out = new(string)
		**out = **in
	}
	if in.SchemaSuffix != nil {
		in, out := &in.SchemaSuffix, &out.SchemaSuffix
		*out = new(string)
		**out = **in
	}
	if in.TablePrefix != nil {
		in, out := &in.TablePrefix, &out.TablePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceCompilationOverridesInitParameters.
func (in *WorkspaceCompilationOverridesInitParameters) DeepCopy() *WorkspaceCompilationOverridesInitParameters {
	if in == nil {
		return nil
	}
	out := new(WorkspaceCompilationOverridesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceCompilationOverridesObservation) DeepCopyInto(out *WorkspaceCompilationOverridesObservation) {
	*out = *in
	if in.DefaultDatabase != nil {
		in, out := &in.DefaultDatabase, &out.DefaultDatabase
		*out = new(string)
		**out = **in
	}
	if in.SchemaSuffix != nil {
		in, out := &in.SchemaSuffix, &out.SchemaSuffix
		*out = new(string)
		**out = **in
	}
	if in.TablePrefix != nil {
		in, out := &in.TablePrefix, &out.TablePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceCompilationOverridesObservation.
func (in *WorkspaceCompilationOverridesObservation) DeepCopy() *WorkspaceCompilationOverridesObservation {
	if in == nil {
		return nil
	}
	out := new(WorkspaceCompilationOverridesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceCompilationOverridesParameters) DeepCopyInto(out *WorkspaceCompilationOverridesParameters) {
	*out = *in
	if in.DefaultDatabase != nil {
		in, out := &in.DefaultDatabase, &out.DefaultDatabase
		*out = new(string)
		**out = **in
	}
	if in.SchemaSuffix != nil {
		in, out := &in.SchemaSuffix, &out.SchemaSuffix
		*out = new(string)
		**out = **in
	}
	if in.TablePrefix != nil {
		in, out := &in.TablePrefix, &out.TablePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceCompilationOverridesParameters.
func (in *WorkspaceCompilationOverridesParameters) DeepCopy() *WorkspaceCompilationOverridesParameters {
	if in == nil {
		return nil
	}
	out := new(WorkspaceCompilationOverridesParameters)
	in.DeepCopyInto(out)
	return out
}
