// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *Repository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryIAMMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryReleaseConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryWorkflowConfig) Hub() {}
