// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type GitRemoteSettingsInitParameters struct {

	// The name of the Secret Manager secret version to use as an authentication token for Git operations. This secret is for assigning with HTTPS only(for SSH use ssh_authentication_config). Must be in the format projects//secrets//versions/*.
	AuthenticationTokenSecretVersion *string `json:"authenticationTokenSecretVersion,omitempty" tf:"authentication_token_secret_version,omitempty"`

	// The Git remote's default branch name.
	DefaultBranch *string `json:"defaultBranch,omitempty" tf:"default_branch,omitempty"`

	// Authentication fields for remote uris using SSH protocol.
	// Structure is documented below.
	SSHAuthenticationConfig *SSHAuthenticationConfigInitParameters `json:"sshAuthenticationConfig,omitempty" tf:"ssh_authentication_config,omitempty"`

	// The Git remote's URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type GitRemoteSettingsObservation struct {

	// The name of the Secret Manager secret version to use as an authentication token for Git operations. This secret is for assigning with HTTPS only(for SSH use ssh_authentication_config). Must be in the format projects//secrets//versions/*.
	AuthenticationTokenSecretVersion *string `json:"authenticationTokenSecretVersion,omitempty" tf:"authentication_token_secret_version,omitempty"`

	// The Git remote's default branch name.
	DefaultBranch *string `json:"defaultBranch,omitempty" tf:"default_branch,omitempty"`

	// Authentication fields for remote uris using SSH protocol.
	// Structure is documented below.
	SSHAuthenticationConfig *SSHAuthenticationConfigObservation `json:"sshAuthenticationConfig,omitempty" tf:"ssh_authentication_config,omitempty"`

	// (Output)
	// Indicates the status of the Git access token. https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories#TokenStatus
	TokenStatus *string `json:"tokenStatus,omitempty" tf:"token_status,omitempty"`

	// The Git remote's URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type GitRemoteSettingsParameters struct {

	// The name of the Secret Manager secret version to use as an authentication token for Git operations. This secret is for assigning with HTTPS only(for SSH use ssh_authentication_config). Must be in the format projects//secrets//versions/*.
	// +kubebuilder:validation:Optional
	AuthenticationTokenSecretVersion *string `json:"authenticationTokenSecretVersion,omitempty" tf:"authentication_token_secret_version,omitempty"`

	// The Git remote's default branch name.
	// +kubebuilder:validation:Optional
	DefaultBranch *string `json:"defaultBranch" tf:"default_branch,omitempty"`

	// Authentication fields for remote uris using SSH protocol.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	SSHAuthenticationConfig *SSHAuthenticationConfigParameters `json:"sshAuthenticationConfig,omitempty" tf:"ssh_authentication_config,omitempty"`

	// The Git remote's URL.
	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`
}

type RepositoryInitParameters struct {

	// Policy to control how the repository and its child resources are deleted. When set to FORCE, any child resources of this repository will also be deleted. Possible values: DELETE, FORCE. Defaults to DELETE.
	DeletionPolicy *string `json:"deletionPolicy,omitempty" tf:"deletion_policy,omitempty"`

	// Optional. The repository's user-friendly name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Optional. If set, configures this repository to be linked to a Git remote.
	// Structure is documented below.
	GitRemoteSettings *GitRemoteSettingsInitParameters `json:"gitRemoteSettings,omitempty" tf:"git_remote_settings,omitempty"`

	// Optional. The reference to a KMS encryption key. If provided, it will be used to encrypt user data in the repository and all child resources.
	// It is not possible to add or update the encryption key after the repository is created. Example projects/[kms_project_id]/locations/[region]/keyRings/[key_region]/cryptoKeys/[key]
	KMSKeyName *string `json:"kmsKeyName,omitempty" tf:"kms_key_name,omitempty"`

	// Optional. Repository user labels.
	// An object containing a list of "key": value pairs. Example: { "name": "wrench", "mass": "1.3kg", "count": "3" }.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Optional. The name of the Secret Manager secret version to be used to interpolate variables into the .npmrc file for package installation operations. Must be in the format projects//secrets//versions/*. The file itself must be in a JSON format.
	NpmrcEnvironmentVariablesSecretVersion *string `json:"npmrcEnvironmentVariablesSecretVersion,omitempty" tf:"npmrc_environment_variables_secret_version,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The service account to run workflow invocations under.
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// If set, fields of workspaceCompilationOverrides override the default compilation settings that are specified in dataform.json when creating workspace-scoped compilation results.
	// Structure is documented below.
	WorkspaceCompilationOverrides *WorkspaceCompilationOverridesInitParameters `json:"workspaceCompilationOverrides,omitempty" tf:"workspace_compilation_overrides,omitempty"`
}

type RepositoryObservation struct {

	// Policy to control how the repository and its child resources are deleted. When set to FORCE, any child resources of this repository will also be deleted. Possible values: DELETE, FORCE. Defaults to DELETE.
	DeletionPolicy *string `json:"deletionPolicy,omitempty" tf:"deletion_policy,omitempty"`

	// Optional. The repository's user-friendly name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// for all of the labels present on the resource.
	// +mapType=granular
	EffectiveLabels map[string]*string `json:"effectiveLabels,omitempty" tf:"effective_labels,omitempty"`

	// Optional. If set, configures this repository to be linked to a Git remote.
	// Structure is documented below.
	GitRemoteSettings *GitRemoteSettingsObservation `json:"gitRemoteSettings,omitempty" tf:"git_remote_settings,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{region}}/repositories/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Optional. The reference to a KMS encryption key. If provided, it will be used to encrypt user data in the repository and all child resources.
	// It is not possible to add or update the encryption key after the repository is created. Example projects/[kms_project_id]/locations/[region]/keyRings/[key_region]/cryptoKeys/[key]
	KMSKeyName *string `json:"kmsKeyName,omitempty" tf:"kms_key_name,omitempty"`

	// Optional. Repository user labels.
	// An object containing a list of "key": value pairs. Example: { "name": "wrench", "mass": "1.3kg", "count": "3" }.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Optional. The name of the Secret Manager secret version to be used to interpolate variables into the .npmrc file for package installation operations. Must be in the format projects//secrets//versions/*. The file itself must be in a JSON format.
	NpmrcEnvironmentVariablesSecretVersion *string `json:"npmrcEnvironmentVariablesSecretVersion,omitempty" tf:"npmrc_environment_variables_secret_version,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// A reference to the region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The service account to run workflow invocations under.
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// The combination of labels configured directly on the resource
	// and default labels configured on the provider.
	// +mapType=granular
	TerraformLabels map[string]*string `json:"terraformLabels,omitempty" tf:"terraform_labels,omitempty"`

	// If set, fields of workspaceCompilationOverrides override the default compilation settings that are specified in dataform.json when creating workspace-scoped compilation results.
	// Structure is documented below.
	WorkspaceCompilationOverrides *WorkspaceCompilationOverridesObservation `json:"workspaceCompilationOverrides,omitempty" tf:"workspace_compilation_overrides,omitempty"`
}

type RepositoryParameters struct {

	// Policy to control how the repository and its child resources are deleted. When set to FORCE, any child resources of this repository will also be deleted. Possible values: DELETE, FORCE. Defaults to DELETE.
	// +kubebuilder:validation:Optional
	DeletionPolicy *string `json:"deletionPolicy,omitempty" tf:"deletion_policy,omitempty"`

	// Optional. The repository's user-friendly name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Optional. If set, configures this repository to be linked to a Git remote.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	GitRemoteSettings *GitRemoteSettingsParameters `json:"gitRemoteSettings,omitempty" tf:"git_remote_settings,omitempty"`

	// Optional. The reference to a KMS encryption key. If provided, it will be used to encrypt user data in the repository and all child resources.
	// It is not possible to add or update the encryption key after the repository is created. Example projects/[kms_project_id]/locations/[region]/keyRings/[key_region]/cryptoKeys/[key]
	// +kubebuilder:validation:Optional
	KMSKeyName *string `json:"kmsKeyName,omitempty" tf:"kms_key_name,omitempty"`

	// Optional. Repository user labels.
	// An object containing a list of "key": value pairs. Example: { "name": "wrench", "mass": "1.3kg", "count": "3" }.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Optional. The name of the Secret Manager secret version to be used to interpolate variables into the .npmrc file for package installation operations. Must be in the format projects//secrets//versions/*. The file itself must be in a JSON format.
	// +kubebuilder:validation:Optional
	NpmrcEnvironmentVariablesSecretVersion *string `json:"npmrcEnvironmentVariablesSecretVersion,omitempty" tf:"npmrc_environment_variables_secret_version,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// A reference to the region
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// The service account to run workflow invocations under.
	// +kubebuilder:validation:Optional
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// If set, fields of workspaceCompilationOverrides override the default compilation settings that are specified in dataform.json when creating workspace-scoped compilation results.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	WorkspaceCompilationOverrides *WorkspaceCompilationOverridesParameters `json:"workspaceCompilationOverrides,omitempty" tf:"workspace_compilation_overrides,omitempty"`
}

type SSHAuthenticationConfigInitParameters struct {

	// Content of a public SSH key to verify an identity of a remote Git host.
	HostPublicKey *string `json:"hostPublicKey,omitempty" tf:"host_public_key,omitempty"`

	// The name of the Secret Manager secret version to use as a ssh private key for Git operations. Must be in the format projects//secrets//versions/*.
	UserPrivateKeySecretVersion *string `json:"userPrivateKeySecretVersion,omitempty" tf:"user_private_key_secret_version,omitempty"`
}

type SSHAuthenticationConfigObservation struct {

	// Content of a public SSH key to verify an identity of a remote Git host.
	HostPublicKey *string `json:"hostPublicKey,omitempty" tf:"host_public_key,omitempty"`

	// The name of the Secret Manager secret version to use as a ssh private key for Git operations. Must be in the format projects//secrets//versions/*.
	UserPrivateKeySecretVersion *string `json:"userPrivateKeySecretVersion,omitempty" tf:"user_private_key_secret_version,omitempty"`
}

type SSHAuthenticationConfigParameters struct {

	// Content of a public SSH key to verify an identity of a remote Git host.
	// +kubebuilder:validation:Optional
	HostPublicKey *string `json:"hostPublicKey" tf:"host_public_key,omitempty"`

	// The name of the Secret Manager secret version to use as a ssh private key for Git operations. Must be in the format projects//secrets//versions/*.
	// +kubebuilder:validation:Optional
	UserPrivateKeySecretVersion *string `json:"userPrivateKeySecretVersion" tf:"user_private_key_secret_version,omitempty"`
}

type WorkspaceCompilationOverridesInitParameters struct {

	// The default database (Google Cloud project ID).
	DefaultDatabase *string `json:"defaultDatabase,omitempty" tf:"default_database,omitempty"`

	// The suffix that should be appended to all schema (BigQuery dataset ID) names.
	SchemaSuffix *string `json:"schemaSuffix,omitempty" tf:"schema_suffix,omitempty"`

	// The prefix that should be prepended to all table names.
	TablePrefix *string `json:"tablePrefix,omitempty" tf:"table_prefix,omitempty"`
}

type WorkspaceCompilationOverridesObservation struct {

	// The default database (Google Cloud project ID).
	DefaultDatabase *string `json:"defaultDatabase,omitempty" tf:"default_database,omitempty"`

	// The suffix that should be appended to all schema (BigQuery dataset ID) names.
	SchemaSuffix *string `json:"schemaSuffix,omitempty" tf:"schema_suffix,omitempty"`

	// The prefix that should be prepended to all table names.
	TablePrefix *string `json:"tablePrefix,omitempty" tf:"table_prefix,omitempty"`
}

type WorkspaceCompilationOverridesParameters struct {

	// The default database (Google Cloud project ID).
	// +kubebuilder:validation:Optional
	DefaultDatabase *string `json:"defaultDatabase,omitempty" tf:"default_database,omitempty"`

	// The suffix that should be appended to all schema (BigQuery dataset ID) names.
	// +kubebuilder:validation:Optional
	SchemaSuffix *string `json:"schemaSuffix,omitempty" tf:"schema_suffix,omitempty"`

	// The prefix that should be prepended to all table names.
	// +kubebuilder:validation:Optional
	TablePrefix *string `json:"tablePrefix,omitempty" tf:"table_prefix,omitempty"`
}

// RepositorySpec defines the desired state of Repository
type RepositorySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RepositoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryInitParameters `json:"initProvider,omitempty"`
}

// RepositoryStatus defines the observed state of Repository.
type RepositoryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RepositoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Repository is the Schema for the Repositorys API. A resource represents a Dataform Git repository
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp-beta}
type Repository struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RepositorySpec   `json:"spec"`
	Status            RepositoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryList contains a list of Repositorys
type RepositoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Repository `json:"items"`
}

// Repository type metadata.
var (
	Repository_Kind             = "Repository"
	Repository_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Repository_Kind}.String()
	Repository_KindAPIVersion   = Repository_Kind + "." + CRDGroupVersion.String()
	Repository_GroupVersionKind = CRDGroupVersion.WithKind(Repository_Kind)
)

func init() {
	SchemeBuilder.Register(&Repository{}, &RepositoryList{})
}
