// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CodeCompilationConfigInitParameters struct {

	// Optional. The default schema (BigQuery dataset ID) for assertions.
	AssertionSchema *string `json:"assertionSchema,omitempty" tf:"assertion_schema,omitempty"`

	// Optional. The suffix that should be appended to all database (Google Cloud project ID) names.
	DatabaseSuffix *string `json:"databaseSuffix,omitempty" tf:"database_suffix,omitempty"`

	// Optional. The default database (Google Cloud project ID).
	DefaultDatabase *string `json:"defaultDatabase,omitempty" tf:"default_database,omitempty"`

	// Optional. The default BigQuery location to use. Defaults to "US".
	// See the BigQuery docs for a full list of locations: https://cloud.google.com/bigquery/docs/locations.
	DefaultLocation *string `json:"defaultLocation,omitempty" tf:"default_location,omitempty"`

	// Optional. The default schema (BigQuery dataset ID).
	DefaultSchema *string `json:"defaultSchema,omitempty" tf:"default_schema,omitempty"`

	// Optional. The suffix that should be appended to all schema (BigQuery dataset ID) names.
	SchemaSuffix *string `json:"schemaSuffix,omitempty" tf:"schema_suffix,omitempty"`

	// Optional. The prefix that should be prepended to all table names.
	TablePrefix *string `json:"tablePrefix,omitempty" tf:"table_prefix,omitempty"`

	// Optional. User-defined variables that are made available to project code during compilation.
	// An object containing a list of "key": value pairs.
	// Example: { "name": "wrench", "mass": "1.3kg", "count": "3" }.
	// +mapType=granular
	Vars map[string]*string `json:"vars,omitempty" tf:"vars,omitempty"`
}

type CodeCompilationConfigObservation struct {

	// Optional. The default schema (BigQuery dataset ID) for assertions.
	AssertionSchema *string `json:"assertionSchema,omitempty" tf:"assertion_schema,omitempty"`

	// Optional. The suffix that should be appended to all database (Google Cloud project ID) names.
	DatabaseSuffix *string `json:"databaseSuffix,omitempty" tf:"database_suffix,omitempty"`

	// Optional. The default database (Google Cloud project ID).
	DefaultDatabase *string `json:"defaultDatabase,omitempty" tf:"default_database,omitempty"`

	// Optional. The default BigQuery location to use. Defaults to "US".
	// See the BigQuery docs for a full list of locations: https://cloud.google.com/bigquery/docs/locations.
	DefaultLocation *string `json:"defaultLocation,omitempty" tf:"default_location,omitempty"`

	// Optional. The default schema (BigQuery dataset ID).
	DefaultSchema *string `json:"defaultSchema,omitempty" tf:"default_schema,omitempty"`

	// Optional. The suffix that should be appended to all schema (BigQuery dataset ID) names.
	SchemaSuffix *string `json:"schemaSuffix,omitempty" tf:"schema_suffix,omitempty"`

	// Optional. The prefix that should be prepended to all table names.
	TablePrefix *string `json:"tablePrefix,omitempty" tf:"table_prefix,omitempty"`

	// Optional. User-defined variables that are made available to project code during compilation.
	// An object containing a list of "key": value pairs.
	// Example: { "name": "wrench", "mass": "1.3kg", "count": "3" }.
	// +mapType=granular
	Vars map[string]*string `json:"vars,omitempty" tf:"vars,omitempty"`
}

type CodeCompilationConfigParameters struct {

	// Optional. The default schema (BigQuery dataset ID) for assertions.
	// +kubebuilder:validation:Optional
	AssertionSchema *string `json:"assertionSchema,omitempty" tf:"assertion_schema,omitempty"`

	// Optional. The suffix that should be appended to all database (Google Cloud project ID) names.
	// +kubebuilder:validation:Optional
	DatabaseSuffix *string `json:"databaseSuffix,omitempty" tf:"database_suffix,omitempty"`

	// Optional. The default database (Google Cloud project ID).
	// +kubebuilder:validation:Optional
	DefaultDatabase *string `json:"defaultDatabase,omitempty" tf:"default_database,omitempty"`

	// Optional. The default BigQuery location to use. Defaults to "US".
	// See the BigQuery docs for a full list of locations: https://cloud.google.com/bigquery/docs/locations.
	// +kubebuilder:validation:Optional
	DefaultLocation *string `json:"defaultLocation,omitempty" tf:"default_location,omitempty"`

	// Optional. The default schema (BigQuery dataset ID).
	// +kubebuilder:validation:Optional
	DefaultSchema *string `json:"defaultSchema,omitempty" tf:"default_schema,omitempty"`

	// Optional. The suffix that should be appended to all schema (BigQuery dataset ID) names.
	// +kubebuilder:validation:Optional
	SchemaSuffix *string `json:"schemaSuffix,omitempty" tf:"schema_suffix,omitempty"`

	// Optional. The prefix that should be prepended to all table names.
	// +kubebuilder:validation:Optional
	TablePrefix *string `json:"tablePrefix,omitempty" tf:"table_prefix,omitempty"`

	// Optional. User-defined variables that are made available to project code during compilation.
	// An object containing a list of "key": value pairs.
	// Example: { "name": "wrench", "mass": "1.3kg", "count": "3" }.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Vars map[string]*string `json:"vars,omitempty" tf:"vars,omitempty"`
}

type ErrorStatusInitParameters struct {
}

type ErrorStatusObservation struct {

	// (Output)
	// The status code, which should be an enum value of google.rpc.Code.
	Code *float64 `json:"code,omitempty" tf:"code,omitempty"`

	// (Output)
	// A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`
}

type ErrorStatusParameters struct {
}

type RecentScheduledReleaseRecordsInitParameters struct {
}

type RecentScheduledReleaseRecordsObservation struct {

	// (Output)
	// The name of the created compilation result, if one was successfully created. Must be in the format projects//locations//repositories//compilationResults/.
	CompilationResult *string `json:"compilationResult,omitempty" tf:"compilation_result,omitempty"`

	// (Output)
	// The error status encountered upon this attempt to create the compilation result, if the attempt was unsuccessful.
	// Structure is documented below.
	ErrorStatus []ErrorStatusObservation `json:"errorStatus,omitempty" tf:"error_status,omitempty"`

	// (Output)
	// The timestamp of this release attempt.
	ReleaseTime *string `json:"releaseTime,omitempty" tf:"release_time,omitempty"`
}

type RecentScheduledReleaseRecordsParameters struct {
}

type RepositoryReleaseConfigInitParameters struct {

	// Optional. If set, fields of codeCompilationConfig override the default compilation settings that are specified in dataform.json.
	// Structure is documented below.
	CodeCompilationConfig *CodeCompilationConfigInitParameters `json:"codeCompilationConfig,omitempty" tf:"code_compilation_config,omitempty"`

	// Optional. Optional schedule (in cron format) for automatic creation of compilation results.
	CronSchedule *string `json:"cronSchedule,omitempty" tf:"cron_schedule,omitempty"`

	// Git commit/tag/branch name at which the repository should be compiled. Must exist in the remote repository.
	GitCommitish *string `json:"gitCommitish,omitempty" tf:"git_commitish,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/cluster/dataform/v1beta1.Repository
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("project",false)
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Repository in dataform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Repository in dataform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.Selector `json:"projectSelector,omitempty" tf:"-"`

	// Optional. Specifies the time zone to be used when interpreting cronSchedule. Must be a time zone name from the time zone database (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If left unspecified, the default is UTC.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type RepositoryReleaseConfigObservation struct {

	// Optional. If set, fields of codeCompilationConfig override the default compilation settings that are specified in dataform.json.
	// Structure is documented below.
	CodeCompilationConfig *CodeCompilationConfigObservation `json:"codeCompilationConfig,omitempty" tf:"code_compilation_config,omitempty"`

	// Optional. Optional schedule (in cron format) for automatic creation of compilation results.
	CronSchedule *string `json:"cronSchedule,omitempty" tf:"cron_schedule,omitempty"`

	// Git commit/tag/branch name at which the repository should be compiled. Must exist in the remote repository.
	GitCommitish *string `json:"gitCommitish,omitempty" tf:"git_commitish,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{region}}/repositories/{{repository}}/releaseConfigs/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Records of the 10 most recent scheduled release attempts, ordered in in descending order of releaseTime. Updated whenever automatic creation of a compilation result is triggered by cronSchedule.
	// Structure is documented below.
	RecentScheduledReleaseRecords []RecentScheduledReleaseRecordsObservation `json:"recentScheduledReleaseRecords,omitempty" tf:"recent_scheduled_release_records,omitempty"`

	// A reference to the region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// A reference to the Dataform repository
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Optional. Specifies the time zone to be used when interpreting cronSchedule. Must be a time zone name from the time zone database (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If left unspecified, the default is UTC.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type RepositoryReleaseConfigParameters struct {

	// Optional. If set, fields of codeCompilationConfig override the default compilation settings that are specified in dataform.json.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	CodeCompilationConfig *CodeCompilationConfigParameters `json:"codeCompilationConfig,omitempty" tf:"code_compilation_config,omitempty"`

	// Optional. Optional schedule (in cron format) for automatic creation of compilation results.
	// +kubebuilder:validation:Optional
	CronSchedule *string `json:"cronSchedule,omitempty" tf:"cron_schedule,omitempty"`

	// Git commit/tag/branch name at which the repository should be compiled. Must exist in the remote repository.
	// +kubebuilder:validation:Optional
	GitCommitish *string `json:"gitCommitish,omitempty" tf:"git_commitish,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/cluster/dataform/v1beta1.Repository
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("project",false)
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Repository in dataform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Repository in dataform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.Selector `json:"projectSelector,omitempty" tf:"-"`

	// A reference to the region
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/cluster/dataform/v1beta1.Repository
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("region",false)
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Reference to a Repository in dataform to populate region.
	// +kubebuilder:validation:Optional
	RegionRef *v1.Reference `json:"regionRef,omitempty" tf:"-"`

	// Selector for a Repository in dataform to populate region.
	// +kubebuilder:validation:Optional
	RegionSelector *v1.Selector `json:"regionSelector,omitempty" tf:"-"`

	// A reference to the Dataform repository
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/cluster/dataform/v1beta1.Repository
	// +kubebuilder:validation:Optional
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Reference to a Repository in dataform to populate repository.
	// +kubebuilder:validation:Optional
	RepositoryRef *v1.Reference `json:"repositoryRef,omitempty" tf:"-"`

	// Selector for a Repository in dataform to populate repository.
	// +kubebuilder:validation:Optional
	RepositorySelector *v1.Selector `json:"repositorySelector,omitempty" tf:"-"`

	// Optional. Specifies the time zone to be used when interpreting cronSchedule. Must be a time zone name from the time zone database (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If left unspecified, the default is UTC.
	// +kubebuilder:validation:Optional
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

// RepositoryReleaseConfigSpec defines the desired state of RepositoryReleaseConfig
type RepositoryReleaseConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RepositoryReleaseConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryReleaseConfigInitParameters `json:"initProvider,omitempty"`
}

// RepositoryReleaseConfigStatus defines the observed state of RepositoryReleaseConfig.
type RepositoryReleaseConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RepositoryReleaseConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RepositoryReleaseConfig is the Schema for the RepositoryReleaseConfigs API. A resource represents a Dataform release configuration
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp-beta}
type RepositoryReleaseConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gitCommitish) || (has(self.initProvider) && has(self.initProvider.gitCommitish))",message="spec.forProvider.gitCommitish is a required parameter"
	Spec   RepositoryReleaseConfigSpec   `json:"spec"`
	Status RepositoryReleaseConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryReleaseConfigList contains a list of RepositoryReleaseConfigs
type RepositoryReleaseConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepositoryReleaseConfig `json:"items"`
}

// Repository type metadata.
var (
	RepositoryReleaseConfig_Kind             = "RepositoryReleaseConfig"
	RepositoryReleaseConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RepositoryReleaseConfig_Kind}.String()
	RepositoryReleaseConfig_KindAPIVersion   = RepositoryReleaseConfig_Kind + "." + CRDGroupVersion.String()
	RepositoryReleaseConfig_GroupVersionKind = CRDGroupVersion.WithKind(RepositoryReleaseConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&RepositoryReleaseConfig{}, &RepositoryReleaseConfigList{})
}
