apiVersion: cloudplatform.gcp-beta.upbound.io/v1beta1
kind: ProjectServiceIdentity
metadata:
  annotations:
    meta.upbound.io/example-id: cloudplatform/v1beta1/projectserviceidentity
  labels:
    testing.upbound.io/example-name: hc_sa
  name: hc-sa
spec:
  forProvider:
    project: ${data.google_project.project.project_id}
    provider: ${google-beta}
    service: healthcare.googleapis.com
