# SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: cloudplatform.gcp-beta.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: cloudplatform/v1beta1/serviceaccount
  labels:
    testing.upbound.io/example-name: service_account
  name: service-account
spec:
  forProvider:
    displayName: Upbound GCP Beta Example Service Account
