// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type IncludedTargetsInitParameters struct {

	// The action's database (Google Cloud project ID).
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// The workflow's name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The action's schema (BigQuery dataset ID), within database.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`
}

type IncludedTargetsObservation struct {

	// The action's database (Google Cloud project ID).
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// The workflow's name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The action's schema (BigQuery dataset ID), within database.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`
}

type IncludedTargetsParameters struct {

	// The action's database (Google Cloud project ID).
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// The workflow's name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The action's schema (BigQuery dataset ID), within database.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`
}

type InvocationConfigInitParameters struct {

	// Optional. When set to true, any incremental tables will be fully refreshed.
	FullyRefreshIncrementalTablesEnabled *bool `json:"fullyRefreshIncrementalTablesEnabled,omitempty" tf:"fully_refresh_incremental_tables_enabled,omitempty"`

	// Optional. The set of tags to include.
	IncludedTags []*string `json:"includedTags,omitempty" tf:"included_tags,omitempty"`

	// Optional. The set of action identifiers to include.
	// Structure is documented below.
	IncludedTargets []IncludedTargetsInitParameters `json:"includedTargets,omitempty" tf:"included_targets,omitempty"`

	// Optional. The service account to run workflow invocations under.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/namespaced/cloudplatform/v1beta1.ServiceAccount
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("email",true)
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// Reference to a ServiceAccount in cloudplatform to populate serviceAccount.
	// +kubebuilder:validation:Optional
	ServiceAccountRef *v1.NamespacedReference `json:"serviceAccountRef,omitempty" tf:"-"`

	// Selector for a ServiceAccount in cloudplatform to populate serviceAccount.
	// +kubebuilder:validation:Optional
	ServiceAccountSelector *v1.NamespacedSelector `json:"serviceAccountSelector,omitempty" tf:"-"`

	// Optional. When set to true, transitive dependencies of included actions will be executed.
	TransitiveDependenciesIncluded *bool `json:"transitiveDependenciesIncluded,omitempty" tf:"transitive_dependencies_included,omitempty"`

	// Optional. When set to true, transitive dependents of included actions will be executed.
	TransitiveDependentsIncluded *bool `json:"transitiveDependentsIncluded,omitempty" tf:"transitive_dependents_included,omitempty"`
}

type InvocationConfigObservation struct {

	// Optional. When set to true, any incremental tables will be fully refreshed.
	FullyRefreshIncrementalTablesEnabled *bool `json:"fullyRefreshIncrementalTablesEnabled,omitempty" tf:"fully_refresh_incremental_tables_enabled,omitempty"`

	// Optional. The set of tags to include.
	IncludedTags []*string `json:"includedTags,omitempty" tf:"included_tags,omitempty"`

	// Optional. The set of action identifiers to include.
	// Structure is documented below.
	IncludedTargets []IncludedTargetsObservation `json:"includedTargets,omitempty" tf:"included_targets,omitempty"`

	// Optional. The service account to run workflow invocations under.
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// Optional. When set to true, transitive dependencies of included actions will be executed.
	TransitiveDependenciesIncluded *bool `json:"transitiveDependenciesIncluded,omitempty" tf:"transitive_dependencies_included,omitempty"`

	// Optional. When set to true, transitive dependents of included actions will be executed.
	TransitiveDependentsIncluded *bool `json:"transitiveDependentsIncluded,omitempty" tf:"transitive_dependents_included,omitempty"`
}

type InvocationConfigParameters struct {

	// Optional. When set to true, any incremental tables will be fully refreshed.
	// +kubebuilder:validation:Optional
	FullyRefreshIncrementalTablesEnabled *bool `json:"fullyRefreshIncrementalTablesEnabled,omitempty" tf:"fully_refresh_incremental_tables_enabled,omitempty"`

	// Optional. The set of tags to include.
	// +kubebuilder:validation:Optional
	IncludedTags []*string `json:"includedTags,omitempty" tf:"included_tags,omitempty"`

	// Optional. The set of action identifiers to include.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	IncludedTargets []IncludedTargetsParameters `json:"includedTargets,omitempty" tf:"included_targets,omitempty"`

	// Optional. The service account to run workflow invocations under.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/namespaced/cloudplatform/v1beta1.ServiceAccount
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("email",true)
	// +kubebuilder:validation:Optional
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// Reference to a ServiceAccount in cloudplatform to populate serviceAccount.
	// +kubebuilder:validation:Optional
	ServiceAccountRef *v1.NamespacedReference `json:"serviceAccountRef,omitempty" tf:"-"`

	// Selector for a ServiceAccount in cloudplatform to populate serviceAccount.
	// +kubebuilder:validation:Optional
	ServiceAccountSelector *v1.NamespacedSelector `json:"serviceAccountSelector,omitempty" tf:"-"`

	// Optional. When set to true, transitive dependencies of included actions will be executed.
	// +kubebuilder:validation:Optional
	TransitiveDependenciesIncluded *bool `json:"transitiveDependenciesIncluded,omitempty" tf:"transitive_dependencies_included,omitempty"`

	// Optional. When set to true, transitive dependents of included actions will be executed.
	// +kubebuilder:validation:Optional
	TransitiveDependentsIncluded *bool `json:"transitiveDependentsIncluded,omitempty" tf:"transitive_dependents_included,omitempty"`
}

type RecentScheduledExecutionRecordsErrorStatusInitParameters struct {
}

type RecentScheduledExecutionRecordsErrorStatusObservation struct {

	// (Output)
	// The status code, which should be an enum value of google.rpc.Code.
	Code *float64 `json:"code,omitempty" tf:"code,omitempty"`

	// (Output)
	// A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`
}

type RecentScheduledExecutionRecordsErrorStatusParameters struct {
}

type RecentScheduledExecutionRecordsInitParameters struct {
}

type RecentScheduledExecutionRecordsObservation struct {

	// (Output)
	// The error status encountered upon this attempt to create the workflow invocation, if the attempt was unsuccessful.
	// Structure is documented below.
	ErrorStatus []RecentScheduledExecutionRecordsErrorStatusObservation `json:"errorStatus,omitempty" tf:"error_status,omitempty"`

	// (Output)
	// The timestamp of this workflow attempt.
	ExecutionTime *string `json:"executionTime,omitempty" tf:"execution_time,omitempty"`

	// (Output)
	// The name of the created workflow invocation, if one was successfully created. In the format projects//locations//repositories//workflowInvocations/.
	WorkflowInvocation *string `json:"workflowInvocation,omitempty" tf:"workflow_invocation,omitempty"`
}

type RecentScheduledExecutionRecordsParameters struct {
}

type RepositoryWorkflowConfigInitParameters struct {

	// Optional. Optional schedule (in cron format) for automatic creation of compilation results.
	CronSchedule *string `json:"cronSchedule,omitempty" tf:"cron_schedule,omitempty"`

	// Optional. If left unset, a default InvocationConfig will be used.
	// Structure is documented below.
	InvocationConfig *InvocationConfigInitParameters `json:"invocationConfig,omitempty" tf:"invocation_config,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/namespaced/dataform/v1beta1.Repository
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("project",false)
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Repository in dataform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Repository in dataform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// The name of the release config whose releaseCompilationResult should be executed. Must be in the format projects//locations//repositories//releaseConfigs/.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/namespaced/dataform/v1beta1.RepositoryReleaseConfig
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ReleaseConfig *string `json:"releaseConfig,omitempty" tf:"release_config,omitempty"`

	// Reference to a RepositoryReleaseConfig in dataform to populate releaseConfig.
	// +kubebuilder:validation:Optional
	ReleaseConfigRef *v1.NamespacedReference `json:"releaseConfigRef,omitempty" tf:"-"`

	// Selector for a RepositoryReleaseConfig in dataform to populate releaseConfig.
	// +kubebuilder:validation:Optional
	ReleaseConfigSelector *v1.NamespacedSelector `json:"releaseConfigSelector,omitempty" tf:"-"`

	// Optional. Specifies the time zone to be used when interpreting cronSchedule. Must be a time zone name from the time zone database (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If left unspecified, the default is UTC.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type RepositoryWorkflowConfigObservation struct {

	// Optional. Optional schedule (in cron format) for automatic creation of compilation results.
	CronSchedule *string `json:"cronSchedule,omitempty" tf:"cron_schedule,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{region}}/repositories/{{repository}}/workflowConfigs/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Optional. If left unset, a default InvocationConfig will be used.
	// Structure is documented below.
	InvocationConfig *InvocationConfigObservation `json:"invocationConfig,omitempty" tf:"invocation_config,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Records of the 10 most recent scheduled execution attempts, ordered in in descending order of executionTime. Updated whenever automatic creation of a workflow invocation is triggered by cronSchedule.
	// Structure is documented below.
	RecentScheduledExecutionRecords []RecentScheduledExecutionRecordsObservation `json:"recentScheduledExecutionRecords,omitempty" tf:"recent_scheduled_execution_records,omitempty"`

	// A reference to the region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The name of the release config whose releaseCompilationResult should be executed. Must be in the format projects//locations//repositories//releaseConfigs/.
	ReleaseConfig *string `json:"releaseConfig,omitempty" tf:"release_config,omitempty"`

	// A reference to the Dataform repository
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Optional. Specifies the time zone to be used when interpreting cronSchedule. Must be a time zone name from the time zone database (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If left unspecified, the default is UTC.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type RepositoryWorkflowConfigParameters struct {

	// Optional. Optional schedule (in cron format) for automatic creation of compilation results.
	// +kubebuilder:validation:Optional
	CronSchedule *string `json:"cronSchedule,omitempty" tf:"cron_schedule,omitempty"`

	// Optional. If left unset, a default InvocationConfig will be used.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	InvocationConfig *InvocationConfigParameters `json:"invocationConfig,omitempty" tf:"invocation_config,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/namespaced/dataform/v1beta1.Repository
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("project",false)
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Repository in dataform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Repository in dataform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// A reference to the region
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/namespaced/dataform/v1beta1.Repository
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("region",false)
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Reference to a Repository in dataform to populate region.
	// +kubebuilder:validation:Optional
	RegionRef *v1.NamespacedReference `json:"regionRef,omitempty" tf:"-"`

	// Selector for a Repository in dataform to populate region.
	// +kubebuilder:validation:Optional
	RegionSelector *v1.NamespacedSelector `json:"regionSelector,omitempty" tf:"-"`

	// The name of the release config whose releaseCompilationResult should be executed. Must be in the format projects//locations//repositories//releaseConfigs/.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/namespaced/dataform/v1beta1.RepositoryReleaseConfig
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ReleaseConfig *string `json:"releaseConfig,omitempty" tf:"release_config,omitempty"`

	// Reference to a RepositoryReleaseConfig in dataform to populate releaseConfig.
	// +kubebuilder:validation:Optional
	ReleaseConfigRef *v1.NamespacedReference `json:"releaseConfigRef,omitempty" tf:"-"`

	// Selector for a RepositoryReleaseConfig in dataform to populate releaseConfig.
	// +kubebuilder:validation:Optional
	ReleaseConfigSelector *v1.NamespacedSelector `json:"releaseConfigSelector,omitempty" tf:"-"`

	// A reference to the Dataform repository
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp-beta/apis/namespaced/dataform/v1beta1.Repository
	// +kubebuilder:validation:Optional
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Reference to a Repository in dataform to populate repository.
	// +kubebuilder:validation:Optional
	RepositoryRef *v1.NamespacedReference `json:"repositoryRef,omitempty" tf:"-"`

	// Selector for a Repository in dataform to populate repository.
	// +kubebuilder:validation:Optional
	RepositorySelector *v1.NamespacedSelector `json:"repositorySelector,omitempty" tf:"-"`

	// Optional. Specifies the time zone to be used when interpreting cronSchedule. Must be a time zone name from the time zone database (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If left unspecified, the default is UTC.
	// +kubebuilder:validation:Optional
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

// RepositoryWorkflowConfigSpec defines the desired state of RepositoryWorkflowConfig
type RepositoryWorkflowConfigSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RepositoryWorkflowConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryWorkflowConfigInitParameters `json:"initProvider,omitempty"`
}

// RepositoryWorkflowConfigStatus defines the observed state of RepositoryWorkflowConfig.
type RepositoryWorkflowConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RepositoryWorkflowConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RepositoryWorkflowConfig is the Schema for the RepositoryWorkflowConfigs API. A resource represents a Dataform workflow configuration
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp-beta}
type RepositoryWorkflowConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RepositoryWorkflowConfigSpec   `json:"spec"`
	Status            RepositoryWorkflowConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryWorkflowConfigList contains a list of RepositoryWorkflowConfigs
type RepositoryWorkflowConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepositoryWorkflowConfig `json:"items"`
}

// Repository type metadata.
var (
	RepositoryWorkflowConfig_Kind             = "RepositoryWorkflowConfig"
	RepositoryWorkflowConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RepositoryWorkflowConfig_Kind}.String()
	RepositoryWorkflowConfig_KindAPIVersion   = RepositoryWorkflowConfig_Kind + "." + CRDGroupVersion.String()
	RepositoryWorkflowConfig_GroupVersionKind = CRDGroupVersion.WithKind(RepositoryWorkflowConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&RepositoryWorkflowConfig{}, &RepositoryWorkflowConfigList{})
}
