// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1beta1 "github.com/upbound/provider-gcp-beta/apis/namespaced/cloudplatform/v1beta1"
	v1beta1compute "github.com/upbound/provider-gcp-beta/apis/namespaced/compute/v1beta1"
	v1beta1container "github.com/upbound/provider-gcp-beta/apis/namespaced/container/v1beta1"
	v1beta1networksecurity "github.com/upbound/provider-gcp-beta/apis/namespaced/networksecurity/v1beta1"
	v1alpha1 "github.com/upbound/provider-gcp-beta/apis/namespaced/v1alpha1"
	v1beta1namespaced "github.com/upbound/provider-gcp-beta/apis/namespaced/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1beta1.SchemeBuilder.AddToScheme,
		v1beta1compute.SchemeBuilder.AddToScheme,
		v1beta1container.SchemeBuilder.AddToScheme,
		v1beta1networksecurity.SchemeBuilder.AddToScheme,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1beta1namespaced.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
