// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *HealthCheck) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RegionBackendService) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RegionSecurityPolicy) Hub() {}
