//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DdosProtectionConfigInitParameters) DeepCopyInto(out *DdosProtectionConfigInitParameters) {
	*out = *in
	if in.DdosProtection != nil {
		in, out := &in.DdosProtection, &out.DdosProtection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DdosProtectionConfigInitParameters.
func (in *DdosProtectionConfigInitParameters) DeepCopy() *DdosProtectionConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(DdosProtectionConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DdosProtectionConfigObservation) DeepCopyInto(out *DdosProtectionConfigObservation) {
	*out = *in
	if in.DdosProtection != nil {
		in, out := &in.DdosProtection, &out.DdosProtection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DdosProtectionConfigObservation.
func (in *DdosProtectionConfigObservation) DeepCopy() *DdosProtectionConfigObservation {
	if in == nil {
		return nil
	}
	out := new(DdosProtectionConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DdosProtectionConfigParameters) DeepCopyInto(out *DdosProtectionConfigParameters) {
	*out = *in
	if in.DdosProtection != nil {
		in, out := &in.DdosProtection, &out.DdosProtection
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DdosProtectionConfigParameters.
func (in *DdosProtectionConfigParameters) DeepCopy() *DdosProtectionConfigParameters {
	if in == nil {
		return nil
	}
	out := new(DdosProtectionConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSecurityPolicy) DeepCopyInto(out *RegionSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSecurityPolicy.
func (in *RegionSecurityPolicy) DeepCopy() *RegionSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(RegionSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegionSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSecurityPolicyInitParameters) DeepCopyInto(out *RegionSecurityPolicyInitParameters) {
	*out = *in
	if in.DdosProtectionConfig != nil {
		in, out := &in.DdosProtectionConfig, &out.DdosProtectionConfig
		*out = new(DdosProtectionConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UserDefinedFields != nil {
		in, out := &in.UserDefinedFields, &out.UserDefinedFields
		*out = make([]UserDefinedFieldsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSecurityPolicyInitParameters.
func (in *RegionSecurityPolicyInitParameters) DeepCopy() *RegionSecurityPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(RegionSecurityPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSecurityPolicyList) DeepCopyInto(out *RegionSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RegionSecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSecurityPolicyList.
func (in *RegionSecurityPolicyList) DeepCopy() *RegionSecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(RegionSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegionSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSecurityPolicyObservation) DeepCopyInto(out *RegionSecurityPolicyObservation) {
	*out = *in
	if in.DdosProtectionConfig != nil {
		in, out := &in.DdosProtectionConfig, &out.DdosProtectionConfig
		*out = new(DdosProtectionConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Fingerprint != nil {
		in, out := &in.Fingerprint, &out.Fingerprint
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PolicyID != nil {
		in, out := &in.PolicyID, &out.PolicyID
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SelfLink != nil {
		in, out := &in.SelfLink, &out.SelfLink
		*out = new(string)
		**out = **in
	}
	if in.SelfLinkWithPolicyID != nil {
		in, out := &in.SelfLinkWithPolicyID, &out.SelfLinkWithPolicyID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UserDefinedFields != nil {
		in, out := &in.UserDefinedFields, &out.UserDefinedFields
		*out = make([]UserDefinedFieldsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSecurityPolicyObservation.
func (in *RegionSecurityPolicyObservation) DeepCopy() *RegionSecurityPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(RegionSecurityPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSecurityPolicyParameters) DeepCopyInto(out *RegionSecurityPolicyParameters) {
	*out = *in
	if in.DdosProtectionConfig != nil {
		in, out := &in.DdosProtectionConfig, &out.DdosProtectionConfig
		*out = new(DdosProtectionConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UserDefinedFields != nil {
		in, out := &in.UserDefinedFields, &out.UserDefinedFields
		*out = make([]UserDefinedFieldsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSecurityPolicyParameters.
func (in *RegionSecurityPolicyParameters) DeepCopy() *RegionSecurityPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(RegionSecurityPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSecurityPolicySpec) DeepCopyInto(out *RegionSecurityPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSecurityPolicySpec.
func (in *RegionSecurityPolicySpec) DeepCopy() *RegionSecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RegionSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSecurityPolicyStatus) DeepCopyInto(out *RegionSecurityPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSecurityPolicyStatus.
func (in *RegionSecurityPolicyStatus) DeepCopy() *RegionSecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RegionSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedFieldsInitParameters) DeepCopyInto(out *UserDefinedFieldsInitParameters) {
	*out = *in
	if in.Base != nil {
		in, out := &in.Base, &out.Base
		*out = new(string)
		**out = **in
	}
	if in.Mask != nil {
		in, out := &in.Mask, &out.Mask
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Offset != nil {
		in, out := &in.Offset, &out.Offset
		*out = new(float64)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedFieldsInitParameters.
func (in *UserDefinedFieldsInitParameters) DeepCopy() *UserDefinedFieldsInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserDefinedFieldsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedFieldsObservation) DeepCopyInto(out *UserDefinedFieldsObservation) {
	*out = *in
	if in.Base != nil {
		in, out := &in.Base, &out.Base
		*out = new(string)
		**out = **in
	}
	if in.Mask != nil {
		in, out := &in.Mask, &out.Mask
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Offset != nil {
		in, out := &in.Offset, &out.Offset
		*out = new(float64)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedFieldsObservation.
func (in *UserDefinedFieldsObservation) DeepCopy() *UserDefinedFieldsObservation {
	if in == nil {
		return nil
	}
	out := new(UserDefinedFieldsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserDefinedFieldsParameters) DeepCopyInto(out *UserDefinedFieldsParameters) {
	*out = *in
	if in.Base != nil {
		in, out := &in.Base, &out.Base
		*out = new(string)
		**out = **in
	}
	if in.Mask != nil {
		in, out := &in.Mask, &out.Mask
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Offset != nil {
		in, out := &in.Offset, &out.Offset
		*out = new(float64)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserDefinedFieldsParameters.
func (in *UserDefinedFieldsParameters) DeepCopy() *UserDefinedFieldsParameters {
	if in == nil {
		return nil
	}
	out := new(UserDefinedFieldsParameters)
	in.DeepCopyInto(out)
	return out
}
