# SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: gcp-beta.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  projectID: official-provider-testing
  credentials:
    source: Secret
    secretRef:
      name: provider-creds
      namespace: upbound-system
      key: creds
